# CPDS in Python Lab - Introduction to Packages and NumPy




## 1. Why do we need Python packages?

A **module** is a single Python file containing reusable variables, functions or classes.

A **package** is a collection of related modules that provides tools for a particular type of work.

Instead of writing every numerical algorithm ourselves, we can use packages containing functions that are already implemented and tested.

Examples:

| Package | Main use |
|---|---|
| NumPy | Numerical arrays and computations |
| Matplotlib | Plotting and visualization |
| Pandas | Data analysis |
| SciPy | Scientific computing |
| Scikit-learn | Machine learning |

### Question 1
Suppose we want to calculate the square root of 25. Can Python already provide a function for this instead of us writing the algorithm ourselves?


In [ ]:
sqrt(25)

NameError: name 'sqrt' is not defined

In [ ]:
25**(1/2)

5.0

In [ ]:
pow(25,1/2)

5.0

In [ ]:
import math

In [ ]:
math.log(25,10)

1.3979400086720375

In [ ]:
import numpy

In [ ]:
numpy.sqrt(25)

np.float64(5.0)

The `sqrt()` function already exists inside the `math` module.



## 2. How do we import a package?

Before using a package, Python must know that we want to use it.

The general syntax is:

```python
import package_name
```

For scientific computing, NumPy is normally imported as

```python
import numpy as np
```

Here, `np` is simply a short **alias** for `numpy`.

### Question 2
Import NumPy using the standard alias `np` and check the installed NumPy version.


In [ ]:
import numpy as np

In [ ]:
np.sqrt(25)

np.float64(5.0)

In [ ]:
numpy.__version__

'2.1.3'

In [ ]:
np.__version__

'2.1.3'

deprecated

## 3. What is a NumPy array?

The main object in NumPy is the **ndarray**, or N-dimensional array.

A Python list may contain general objects, but a NumPy array is optimized for storing and processing numerical data efficiently.

### Question 3
Create the vector

$
x =
\begin{bmatrix}
2 & 4 & 6 & 8 & 10
\end{bmatrix}
$

as a NumPy array.


In [ ]:
x = [2,3,4,5,6,7]

In [ ]:
np.array(x)

array([2, 3, 4, 5, 6, 7])

In [ ]:
numpy.array(x)

array([2, 3, 4, 5, 6, 7])

In [ ]:
x

[2, 3, 4, 5, 6, 7]

In [ ]:
x = numpy.array(x)

In [ ]:
x

array([2, 3, 4, 5, 6, 7])

In [ ]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [ ]:
for i in [1,2,3]*20:
  print(i**2)

1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9
1
4
9


In [ ]:
np.array([1,2,3])**2

array([1, 4, 9])

### Question 4
Can NumPy also represent a matrix?

$
A =
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}.
$


In [ ]:
A = [[1,2,3],[2,3,4]]

In [ ]:
A = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [ ]:
A

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [ ]:
A = np.array(A)

In [ ]:
A

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
A**2

array([[ 1,  4,  9],
       [ 4,  9, 16]])

## 4. Create NumPy arrays automatically?

### Question 5
Create:

1. a \(2 x 3\) matrix of zeros,
2. a \(2 x 3\) matrix of ones.


In [ ]:
[[0,0,0],[0,0,0]]

[[0, 0, 0], [0, 0, 0]]

In [ ]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
[[0]*3,[0,0,0]]

[[0, 0, 0], [0, 0, 0]]

In [ ]:
np.array([[0]*3,[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Useful NumPy functions include:

- `np.zeros(shape)` — creates an array filled with zeros,
- `np.ones(shape)` — creates an array filled with ones,
- `np.arange(start, stop, step)` — creates regularly spaced values using a step size,
- `np.linspace(start, stop, number)` — creates a specified number of equally spaced values.

### Question 6
Generate the numbers

\[
0,2,4,6,8
\]

using `arange()`.


In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [ ]:
for i in range(-10,0,2):
  print(i)

-10
-8
-6
-4
-2


In `arange(start, stop, step)`.

### Question 7
For a simulation from \(t=0\) to \(t=10\) seconds, generate exactly 11 equally spaced time points.

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Question 8
For the matrix

$
A =
\begin{bmatrix}
10 & 20 & 30\\
40 & 50 & 60
\end{bmatrix},
$

find its shape, number of dimensions, total number of elements and data type.


In [ ]:
A = np.array([[10,20,30],[40,50,60]])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
len(A)

2

In [ ]:
A.elements

AttributeError: 'numpy.ndarray' object has no attribute 'elements'

In [ ]:
A.size

6

In [ ]:
A = [[10,20,30],
    [40,50,60],
     [40,50,60],
     [40,50,60],
     [40,50,60],
     [40,50,60]]

In [ ]:
len(A[0])+len(A[1])

6

In [ ]:
A = np.array(A)

In [ ]:
A.size

18

In [ ]:
type(A)

numpy.ndarray

- `shape` — dimensions of the array,
- `ndim` — number of dimensions,
- `size` — total number of elements,
- `dtype` — data type of the elements.

## 6. Access elements of a NumPy array

### Question 9
Using the matrix below:

1. print the element in the first row and second column,
2. print the entire second row,
3. print the entire third column.


In [ ]:
[1,0,2]

[1, 0, 2]

In [ ]:
[1,0,2][1]

0

In [ ]:
[1,0,2][2]

2

In [ ]:
[1,0,2][-2]

0

In [ ]:
np.array([1,0,2])

array([1, 0, 2])

In [ ]:
np.array([1,0,2]).shape

(3,)

In [ ]:
np.array([1,0,2])[0]

np.int64(1)

int32, int64, float32, float64

In [ ]:
np.array([1,0,2],dtype=numpy.int32)[0]

np.int32(1)

In [ ]:
np.array([1,0,2],dtype=numpy.float32)[0]

np.float32(1.0)

In [ ]:
[[1,2],[2,3]][1]

[2, 3]

In [ ]:
[[1,2],[2,3]][1][1]

3

In [ ]:
np.array([[1,2],[2,3]])[1,1]

np.int64(3)

In [ ]:
np.array([[1,2],[2,3]])[1:]

array([[2, 3]])

NumPy uses **zero-based indexing**, like Python lists.

For a one-dimensional array:

```python
x[0]
```

is the first element.

For a two-dimensional array:

```python
A[row, column]
```

selects an element.

The symbol `:` means take all entries along that direction.

Therefore:

```python
A[1, :]
```

means: second row, all columns.

and

```python
A[:, 2]
```

means: all rows, third column.


## 7. Arithmetic with NumPy arrays

One of the biggest advantages of NumPy is that arithmetic can be performed on entire arrays directly.

This is called **vectorization**.

Instead of processing each element manually with a loop, NumPy applies the operation to the complete array.

### Question 10
Let

$x = [1,2,3,4].$

Find:

1. $2x$,
2. $x+10$,
3. $x^2$.


In [ ]:
[1,2,3,4]+[4,5,6,7]

[1, 2, 3, 4, 4, 5, 6, 7]

In [ ]:
[1,2,3,4]**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
np.array([1,2,3,4]) + np.array([4,5,6,7])

array([ 5,  7,  9, 11])

In [ ]:
3*np.array([1,2,3,4])

array([ 3,  6,  9, 12])

In [ ]:
np.array([1,2,3,4]) + 10

array([11, 12, 13, 14])

## 8. Element-wise operations versus matrix multiplication

### Question 11
Compare `A * B` and `A @ B` for the matrices below.


In [ ]:
A = np.array([[1,2,3],[3,4,5]])

In [ ]:
B = np.array([[1,2,3],[3,4,5]])

In [ ]:
A *B

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [ ]:
A @B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
np.transpose(A)

array([[1, 3],
       [2, 4],
       [3, 5]])

In [ ]:
A.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [ ]:
A.T * B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
A.T @ B

array([[10, 14, 18],
       [14, 20, 26],
       [18, 26, 34]])

In [ ]:
np.matmul(A.T,B)

array([[10, 14, 18],
       [14, 20, 26],
       [18, 26, 34]])

In [ ]:
np.array(np.dot(np.array([1,2,3]),np.array([2,3,4])),dtype = numpy.float32)

array(20., dtype=float32)

For NumPy arrays:

```python
A * B
```

performs **element-wise multiplication**.

For matrices:

```python
A @ B
```

performs **matrix multiplication**.

These are different operations.

## 9. Can NumPy apply mathematical functions to a complete array?

NumPy provides **vectorized mathematical functions**.


Some

- `np.sqrt(x)` — square root,
- `np.exp(x)` — exponential,
- `np.log(x)` — natural logarithm,
- `np.sin(x)` — sine,
- `np.cos(x)` — cosine,
- `np.abs(x)` — absolute value.

### Question 12
For

$x=[1,4,9,16,25],$

calculate the square root of every element using one command.


In [ ]:
import numpy as np

In [ ]:
x = [1,4,9,16,25]
x = np.array(x)

In [ ]:
np.sqrt(x)

array([1., 2., 3., 4., 5.])

In [ ]:
np.sin(x)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175])

In [ ]:
np.cos(x)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281])

## 10. Basic statistical functions


- `np.sum(x)` — sum,
- `np.mean(x)` — arithmetic mean,
- `np.median(x)` — median,
- `np.std(x)` — standard deviation,
- `np.min(x)` — minimum,
- `np.max(x)` — maximum.

(These are only some of the functions not all)

### Question 13
The temperatures measured during five experiments are

$[28.5,30.0,29.5,31.0,27.5].$

Find the mean, minimum and maximum temperatures.


In [ ]:
x

array([ 1,  4,  9, 16, 25])

In [ ]:
np.min(x)

np.int64(1)

In [ ]:
np.max(x)

np.int64(25)

In [ ]:
np.mean(x)

np.float64(11.0)

A vehicle travels with the following measured velocities in m/s:

$v=[0,5,10,15,20,25].$

### Question 14

Using NumPy:

1. create the velocity array,
2. convert every velocity from m/s to km/h using  

   $
   v_{{km/h}}=3.6v_{{m/s}},
   $
   
3. find the average velocity in km/h,
4. find the largest velocity in km/h.

Try the question first before running the solution.


In [ ]:
v = [0,5,10,15,20,25]

In [ ]:
v = np.array(v)

In [ ]:
v

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
np.v*3.6

AttributeError: module 'numpy' has no attribute 'v'

In [ ]:
v_kmh = v*3.6

In [ ]:
np.mean(v_kmh)

np.float64(45.0)

In [ ]:
np.max(v_kmh)

np.float64(90.0)

## Slicing a One-Dimensional Array

**Slicing** means selecting a part of an array.

The general form is

```python
A[start:stop:step]
```

### Question 15
From the array

$A=[10,20,30,40,50,60,70],$

extract the elements `20, 30, 40, 50`.


In [ ]:
A = np.array([10,20,30,40,50,60,70])

In [ ]:
A[1:5]

array([20, 30, 40, 50])

In [ ]:
A[-3:-7]

array([], dtype=int64)

In [ ]:
A[-7:-2]

array([10, 20, 30, 40, 50])

In [ ]:
A[:-2]

array([10, 20, 30, 40, 50])

### Question 16
Using the same array:

1. extract the first four elements,
2. extract all elements from index 3 onward,
3. extract every second element.


In [ ]:
A[0:5]

array([10, 20, 30, 40, 50])

In [ ]:
A[:5]

array([10, 20, 30, 40, 50])

In [ ]:
A[0:7:2]

array([10, 30, 50, 70])

In [ ]:
A[::2]

array([10, 30, 50, 70])

## slicing a Two-Dimensional Array

For a matrix,

```python
A[rows, columns]
```

can be used to select a block of entries.

### Question 17
Given

$
A=
\begin{bmatrix}
1&2&3&4\\
5&6&7&8\\
9&10&11&12
\end{bmatrix},
$

extract the first two rows and the middle two columns.


In [ ]:
A =  np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A[1:1]

array([], shape=(0, 4), dtype=int64)

In [ ]:
A[1][1]

np.int64(6)

In [ ]:
A[1,1]

np.int64(6)

In [ ]:
A[1]

array([5, 6, 7, 8])

In [ ]:
A[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
A[:-2]

array([[1, 2, 3, 4]])

In [ ]:
A[:-3]

array([], shape=(0, 4), dtype=int64)

In [ ]:
A[-3:-1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
A[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A[0,0:2]

array([1, 2])

## Reshaping an Array


### Question 18
Create the numbers 1 to 12 and reshape them into a \(3\times4\) matrix.


In [ ]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(12).reshape(3,4).T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones(12).reshape(3,4).flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

The function

```python
A.reshape(new_shape)
```

changes the shape while preserving the elements.

### Question 19
Can the same 12 elements be arranged as a \(4 x 3\) matrix?


## Flattening an Array

### Question 20
Convert the following matrix into a one-dimensional array.


A multidimensional array can be converted into a one-dimensional array using

```python
A.flatten()
```

## Transpose of a Matrix


### Question 21
Find the transpose of a \(2 x 3\) matrix and compare the shapes before and after transposition.


In [ ]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
np.transpose(A)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
np.reshape(A.flatten(), (3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A.flatten(0)A

TypeError: order must be str, not int

In [ ]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A.flatten(order = 'F')

NameError: name 'A' is not defined

## Element-wise Array Operations

### Question 22
For

$A=[10,20,30],\qquad B=[2,4,5],$

find:

1. \(A+B\),
2. \(A-B\),
3. \(A\times B\) element by element,
4. \(A/B\) element by element.


In [ ]:
B = A

In [ ]:
A,B

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [ ]:
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [ ]:
A*B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
A/B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Dot Product

### Question 23
Calculate

$[1,2,3]\cdot[4,5,6].$


In [ ]:
np.dot(np.array([1,2,3]),
       np.array([4,5,6]))

np.int64(32)

## Broadcasting

For example, adding

$[10,20,30]$

to every row of

$\begin{bmatrix}
1&2&3\\
4&5&6
\end{bmatrix}$

does not require a loop.

### Question 24
Add the vector `[10, 20, 30]` to every row of the matrix.


In [ ]:
[10,10] +10

TypeError: can only concatenate list (not "int") to list

In [ ]:
np.array([10,10]) +10

array([20, 20])

In [ ]:
A + np.array([10,20,30,40])

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

## Exponential and Natural Logarithm

### Question 25
Evaluate $e^x$ for $x=0,1,2$.


In [ ]:
np.exp(np.array([0,1,2]))

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
np.log(np.array([6,1,2]),10)

TypeError: return arrays must be of ArrayType

In [ ]:
np.log10(np.array([6,1,2]))

array([0.77815125, 0.        , 0.30103   ])

In [ ]:
import math

math.log(10,5)

1.4306765580733933

In [ ]:
np.emath.logn(10,5)

np.float64(0.6989700043360187)

##  Trigonometric Functions

### Question 26
Generate five equally spaced angles from $0$ to $\pi$ and calculate their sine and cosine.


In [ ]:
import numpy as np

In [ ]:
np.linspace(0,np.pi,5)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [ ]:
np.sin(np.linspace(0,np.pi,5))

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

### Question 27
Find the absolute values of

$
[-4,-2,3,-8].
$


In [ ]:
np.abs(np.array([-1,-2,3]))

array([1, 2, 3])

## Location of Maximum and Minimum

### Question 28
For

$
A=[15,8,30,22,10],
$

find:

1. the maximum value,
2. its index,
3. the minimum value,
4. its index.


In [ ]:
np.max(np.array([15,8,30,22]))

np.int64(30)

In [ ]:
np.argmin(np.array([15,8,30,22]))

np.int64(1)

In [ ]:
np.argmax(np.array([15,8]))

np.int64(0)

## Cumulative Sum

### Question 29
Use `np.cumsum()` to calculate the cumulative sum.


In [ ]:
np.cumsum(np.array([1,2,2,3,4]))

array([ 1,  3,  5,  8, 12])

##  Computation Along Rows and Columns


### Question 30
For

$
A=
\begin{bmatrix}
10&20&30\\
40&50&60
\end{bmatrix},
$

find:

1. the sum of each column,
2. the sum of each row,
3. the mean of each column.


In [ ]:
A = np.array([[10,20,30],[40,50,60]])

In [ ]:
np.sum(A)

np.int64(210)

In [ ]:
np.sum(A[1:])

np.int64(150)

In [ ]:
np.sum(A[2:])

np.int64(0)

In [ ]:
np.sum(A, axis=1)

array([ 60, 150])

In [ ]:
np.mean(A, axis=0)

array([25., 35., 45.])

## Boolean Conditions

### Question 31
For

$
A=[12,5,18,7,25,3],
$

check which elements are greater than 10.


In [ ]:
14>=3

True

In [ ]:
np.array([12,35,18,7,25])>=10

array([ True,  True,  True, False,  True])

In [ ]:
np.array([12,35,18,7,25])[np.array([12,35,18,7,25])>=10]

array([12, 35, 18, 25])

## Combining Arrays

### Question 32
Combine

$
A=[1,2,3]
$

and

$
B=[4,5,6].
$


In [ ]:
[1,2,3]+[2,3,4]

[1, 2, 3, 2, 3, 4]

In [ ]:
np.concatenate((np.array([1,2,3]),np.array([2,3,4])))

array([1, 2, 3, 2, 3, 4])

Suppose the displacement of an oscillator is

$x(t)=2\sin(t).$

We want to evaluate this function at several time points.

### Question 33
Generate 9 equally spaced points between \(0\) and \(2\pi\), and calculate

$
x(t)=2\sin(t)
$

without using a loop.


In [ ]:
t = np.linspace(0,2*np.pi,9)

In [ ]:
x_t = 2*np.sin(t)

In [ ]:
x_t

array([ 0.00000000e+00,  1.41421356e+00,  2.00000000e+00,  1.41421356e+00,
        2.44929360e-16, -1.41421356e+00, -2.00000000e+00, -1.41421356e+00,
       -4.89858720e-16])

# Experimental Temperature Data

The temperatures measured at eight time instants are

$
T=[25.0,26.5,28.0,29.2,30.1,29.8,28.7,27.5].
$

### Question 34

Using NumPy:

1. store the measurements in an array,
2. find the mean temperature,
3. find the maximum temperature,
4. determine the index at which the maximum occurs,
5. extract all temperatures greater than the mean,
6. calculate the cumulative sum.


In [ ]:
T = [1,2,3,4,5,6,7,8,9]

In [ ]:
T = np.array(T)

In [ ]:
np.mean(T)

np.float64(5.0)

In [ ]:
np.max(T)

np.int64(9)

In [ ]:
np.argmax(T)

np.int64(8)

In [ ]:
T >np.mean(T)

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
T[T >np.mean(T)]

array([6, 7, 8, 9])

In [ ]:
np.cumsum(T)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

# Motion Data

A moving object's position is measured at equally spaced times:

$x=[0,1.2,2.8,4.9,7.5,10.6].$

The time points are

$t=[0,1,2,3,4,5].$

### Question 35

Using NumPy:

1. create `t`,
2. store the position data,
3. calculate the displacement between consecutive measurements using
4. calculate the average position,
5. determine the maximum position,
6. determine when the maximum position occurs.

In [ ]:
t = np.array([0,1,2,3,4,5])

In [ ]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [ ]:
x = np.array([0,3,4,5,6,6,3,2])

In [ ]:
x[1:]-x[:-1]

array([ 3,  1,  1,  1,  0, -3, -1])

## Creating arrays

```python
np.array(...)
np.zeros(...)
np.ones(...)
np.arange(...)
np.linspace(...)
```

## Array information

```python
A.shape
A.ndim
A.size
A.dtype
```

## Selecting and reshaping

```python
A[index]
A[start:stop]
A[row, column]
A.reshape(...)
A.flatten()
A.T
```

## Arithmetic and linear algebra

```python
A + B
A - B
A * B
A / B
A @ B
np.dot(A, B)
```

## Mathematical functions

```python
np.sqrt(A)
np.exp(A)
np.log(A)
np.sin(A)
np.cos(A)
np.tan(A)
np.abs(A)
```

## Statistical functions

```python
np.sum(A)
np.mean(A)
np.median(A)
np.std(A)
np.var(A)
np.max(A)
np.min(A)
np.argmax(A)
np.argmin(A)
np.cumsum(A)
```

## Filtering

```python
A[A > value]
```


## Question 1 - Number Analysis

Write a Python program that accepts a positive integer and finds:

1. the number of digits,
2. the sum of its digits,
3. the largest digit,
4. the smallest digit.

**Example**

```text
Input: 58327

Number of digits = 5
Sum of digits = 25
Largest digit = 8
Smallest digit = 2
```

In [ ]:
inp = input("give num")

give num16354


In [ ]:
type(inp)

str

In [ ]:
list(inp)

['1', '6', '3', '5', '4']

In [ ]:
inp

'16354'

In [ ]:
[int(inp)]

[16354]

In [ ]:
np.array(list(inp))

array(['1', '6', '3', '5', '4'], dtype='<U1')

In [ ]:
np.array(list(inp),dtype =int)

array([1, 6, 3, 5, 4])

## Question 7

Write a function

```python
prime_numbers(numbers)
```

that accepts a list of integers and returns a new list containing only the prime numbers.

**Example**

```text
Input:
[4, 7, 10, 13, 18, 23, 1]

Output:
[7, 13, 23]
```

In [ ]:
nums_list = [4,7,10,13,18,23,1]

In [ ]:
nums_array = np.array(nums_list)

In [ ]:
nums_array

array([ 4,  7, 10, 13, 18, 23,  1])

In [ ]:
is_prime = lambda n: n>1 and all(n%i!=0 for i in range(2,n))

In [ ]:
np.array([10])%np.array([1,2,34])

array([ 0,  0, 10])

In [ ]:
[10]%[1,2,33]

TypeError: unsupported operand type(s) for %: 'list' and 'list'

In [ ]:
is_prime = lambda n: n>1 and all(n%(np.arange(2,n,1))!=0)

In [ ]:
is_prime(20)

False

In [ ]:
def prime_list(numbers):
  dummy_list = []
  for i in range(len(numbers)):
    if is_prime(numbers[i]):
      dummy_list.append(numbers[i])
  return dummy_list


In [ ]:
nums_array[np.vectorize(is_prime)(nums_array)]

array([ 7, 13, 23])